"""initial schema

Revision ID: da5688e1842c
Revises: 
Create Date: 2026-07-01 07:35:44.147892
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'da5688e1842c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_activity_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('actor_type', sa.Text(), server_default='ADMIN', nullable=False),
    sa.Column('actor_id', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('resource_type', sa.Text(), nullable=False),
    sa.Column('resource_id', sa.Text(), nullable=True),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_admin_activity_logs_created', 'admin_activity_logs', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_admin_activity_logs_lookup', 'admin_activity_logs', ['resource_type', 'resource_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('component_health',
    sa.Column('component_code', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='UNKNOWN', nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_ok_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('UNKNOWN', 'OK', 'DEGRADED', 'DOWN', 'PAUSED')", name='ck_health_status'),
    sa.PrimaryKeyConstraint('component_code')
    )
    op.create_table('data_sources',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('broker', sa.Text(), server_default='TRADINGVIEW', nullable=False),
    sa.Column('account_id', sa.Text(), nullable=True),
    sa.Column('secret_ref', sa.Text(), nullable=True),
    sa.Column('webhook_token_hash', sa.Text(), nullable=True),
    sa.Column('body_secret_hash', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('status', sa.Text(), server_default='UNKNOWN', nullable=False),
    sa.Column('stale_grace_minutes', sa.Integer(), server_default='20', nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('last_ok_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_payload_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.Text(), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('UNKNOWN', 'OK', 'DEGRADED', 'DOWN', 'PAUSED')", name='ck_data_sources_status'),
    sa.CheckConstraint("type IN ('TRADINGVIEW_BAR_WEBHOOK', 'TRADINGVIEW_SIGNAL_WEBHOOK', 'MT5_CONNECTOR', 'MT4_BRIDGE', 'OANDA')", name='ck_data_sources_type'),
    sa.CheckConstraint('stale_grace_minutes > 0', name='ck_data_sources_grace'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('strategies',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('version', sa.Text(), server_default='v1', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('default_config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('symbol_settings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('price_digits', sa.Integer(), server_default='2', nullable=False),
    sa.Column('point_size', sa.Numeric(), nullable=False),
    sa.Column('pip_size', sa.Numeric(), nullable=True),
    sa.Column('sl_buffer_points', sa.Numeric(), server_default='0', nullable=False),
    sa.Column('entry_zone_points', sa.Numeric(), server_default='0', nullable=False),
    sa.Column('max_spread', sa.Numeric(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('entry_zone_points >= 0', name='ck_symbol_entry_zone'),
    sa.CheckConstraint('max_spread IS NULL OR max_spread >= 0', name='ck_symbol_max_spread'),
    sa.CheckConstraint('pip_size IS NULL OR pip_size > 0', name='ck_symbol_pip_size'),
    sa.CheckConstraint('point_size > 0', name='ck_symbol_point_size'),
    sa.CheckConstraint('price_digits BETWEEN 0 AND 8', name='ck_symbol_digits'),
    sa.CheckConstraint('sl_buffer_points >= 0', name='ck_symbol_sl_buffer'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('telegram_groups',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('telegram_chat_id', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), server_default='FREE', nullable=False),
    sa.Column('mode', sa.Text(), server_default='DEMO', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_paused', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_test_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_delivery_status', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("last_delivery_status IS NULL OR last_delivery_status IN ('PENDING', 'SENDING', 'SENT', 'FAILED_RETRYABLE', 'FAILED_PERMANENT', 'SKIPPED')", name='ck_group_last_delivery_status'),
    sa.CheckConstraint("mode IN ('DEMO', 'INTERNAL', 'LIVE')", name='ck_group_mode'),
    sa.CheckConstraint("type IN ('FREE', 'VIP', 'SMC', 'INTERNAL')", name='ck_group_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_chat_id')
    )
    op.create_table('broker_symbol_mappings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('broker', sa.Text(), server_default='TRADINGVIEW', nullable=False),
    sa.Column('canonical_symbol', sa.Text(), nullable=False),
    sa.Column('broker_symbol', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_symbol'], ['symbol_settings.symbol'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'broker_symbol', name='uq_mapping_source_broker'),
    sa.UniqueConstraint('source_id', 'canonical_symbol', name='uq_mapping_source_canonical')
    )
    op.create_index('idx_broker_symbol_mappings_source_symbol', 'broker_symbol_mappings', ['source_id', 'broker_symbol'], unique=False)
    op.create_table('data_source_feeds',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('canonical_symbol', sa.Text(), nullable=False),
    sa.Column('source_symbol', sa.Text(), nullable=False),
    sa.Column('timeframe', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('status', sa.Text(), server_default='UNKNOWN', nullable=False),
    sa.Column('stale_after_minutes', sa.Integer(), nullable=False),
    sa.Column('last_candle_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_payload_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.Text(), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('UNKNOWN', 'WARMUP', 'OK', 'STALE', 'ERROR', 'PAUSED')", name='ck_feed_status'),
    sa.CheckConstraint("timeframe IN ('M5', 'M15', 'H1', 'H4')", name='ck_feed_timeframe'),
    sa.CheckConstraint('stale_after_minutes > 0', name='ck_feed_stale'),
    sa.ForeignKeyConstraint(['canonical_symbol'], ['symbol_settings.symbol'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'canonical_symbol', 'timeframe', name='uq_feed_source_symbol_tf')
    )
    op.create_index('idx_data_source_feeds_matrix', 'data_source_feeds', ['canonical_symbol', 'timeframe', 'source_id'], unique=False)
    op.create_index('idx_data_source_feeds_status', 'data_source_feeds', ['status', 'is_active', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('group_strategy_settings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('setting_code', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('strategy_id', sa.BigInteger(), nullable=False),
    sa.Column('min_confidence', sa.Integer(), server_default='70', nullable=False),
    sa.Column('risk_level', sa.Text(), server_default='MEDIUM', nullable=False),
    sa.Column('send_mode', sa.Text(), server_default='FULL', nullable=False),
    sa.Column('cooldown_minutes', sa.Integer(), server_default='30', nullable=False),
    sa.Column('duplicate_window_minutes', sa.Integer(), server_default='30', nullable=False),
    sa.Column('entry_tolerance_points', sa.Numeric(), server_default='20', nullable=False),
    sa.Column('min_rr', sa.Numeric(), server_default='1.5', nullable=False),
    sa.Column('max_spread', sa.Numeric(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("risk_level IN ('LOW', 'MEDIUM', 'HIGH')", name='ck_gss_risk_level'),
    sa.CheckConstraint("send_mode IN ('BASIC', 'FULL', 'SUMMARY')", name='ck_gss_send_mode'),
    sa.CheckConstraint('cooldown_minutes >= 0', name='ck_gss_cooldown'),
    sa.CheckConstraint('duplicate_window_minutes >= 0', name='ck_gss_dup_window'),
    sa.CheckConstraint('entry_tolerance_points >= 0', name='ck_gss_entry_tol'),
    sa.CheckConstraint('max_spread IS NULL OR max_spread >= 0', name='ck_gss_max_spread'),
    sa.CheckConstraint('min_confidence BETWEEN 0 AND 100', name='ck_gss_min_confidence'),
    sa.CheckConstraint('min_rr > 0', name='ck_gss_min_rr'),
    sa.ForeignKeyConstraint(['group_id'], ['telegram_groups.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'setting_code', name='uq_gss_group_setting_code')
    )
    op.create_index('idx_group_strategy_settings_group_active', 'group_strategy_settings', ['group_id', 'is_active'], unique=False)
    op.create_index('idx_group_strategy_settings_strategy_active', 'group_strategy_settings', ['strategy_id', 'is_active'], unique=False)
    op.create_table('market_candles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('source_code', sa.Text(), nullable=False),
    sa.Column('broker', sa.Text(), server_default='TRADINGVIEW', nullable=False),
    sa.Column('account_id', sa.Text(), nullable=True),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('source_symbol', sa.Text(), nullable=False),
    sa.Column('timeframe', sa.Text(), nullable=False),
    sa.Column('candle_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(), nullable=False),
    sa.Column('high', sa.Numeric(), nullable=False),
    sa.Column('low', sa.Numeric(), nullable=False),
    sa.Column('close', sa.Numeric(), nullable=False),
    sa.Column('volume', sa.Numeric(), nullable=True),
    sa.Column('spread', sa.Numeric(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('payload_hash', sa.Text(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("timeframe IN ('M5', 'M15', 'H1', 'H4')", name='ck_candle_timeframe'),
    sa.CheckConstraint('high >= close', name='ck_candle_high_close'),
    sa.CheckConstraint('high >= low', name='ck_candle_high_low'),
    sa.CheckConstraint('high >= open', name='ck_candle_high_open'),
    sa.CheckConstraint('low <= close', name='ck_candle_low_close'),
    sa.CheckConstraint('low <= open', name='ck_candle_low_open'),
    sa.CheckConstraint('spread IS NULL OR spread >= 0', name='ck_candle_spread'),
    sa.CheckConstraint('volume IS NULL OR volume >= 0', name='ck_candle_volume'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['symbol'], ['symbol_settings.symbol'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'symbol', 'timeframe', 'candle_time', name='uq_candle_key')
    )
    op.create_index('idx_market_candles_lookup', 'market_candles', ['symbol', 'timeframe', sa.literal_column('candle_time DESC')], unique=False)
    op.create_index('idx_market_candles_source_lookup', 'market_candles', ['source_id', 'symbol', 'timeframe', sa.literal_column('candle_time DESC')], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('signal_uid', sa.Text(), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('strategy_code', sa.Text(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('timeframe', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('entry', sa.Numeric(), nullable=True),
    sa.Column('entry_zone_low', sa.Numeric(), nullable=True),
    sa.Column('entry_zone_high', sa.Numeric(), nullable=True),
    sa.Column('sl', sa.Numeric(), nullable=True),
    sa.Column('tp', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_reward', sa.Numeric(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('reason', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('invalid_if', sa.Text(), nullable=True),
    sa.Column('source_candle_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), server_default='CREATED', nullable=False),
    sa.Column('reject_code', sa.Text(), nullable=True),
    sa.Column('reject_message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action IN ('BUY', 'SELL')", name='ck_signal_action'),
    sa.CheckConstraint("reason IS NULL OR jsonb_typeof(reason) = 'array'", name='ck_signal_reason_array'),
    sa.CheckConstraint("status IN ('CREATED', 'REJECTED', 'APPROVED', 'ROUTED', 'QUEUED', 'SENT', 'PARTIAL_SENT', 'PARTIAL_FAILED', 'FAILED', 'SKIPPED_DUPLICATE')", name='ck_signal_status'),
    sa.CheckConstraint("status NOT IN ('APPROVED','ROUTED','QUEUED','SENT','PARTIAL_SENT','PARTIAL_FAILED') OR (entry IS NOT NULL AND sl IS NOT NULL AND tp IS NOT NULL AND risk_reward IS NOT NULL AND confidence IS NOT NULL AND invalid_if IS NOT NULL)", name='ck_signal_complete_when_approved'),
    sa.CheckConstraint("timeframe IN ('M5', 'M15', 'H1', 'H4')", name='ck_signal_timeframe'),
    sa.CheckConstraint("tp IS NULL OR jsonb_typeof(tp) = 'array'", name='ck_signal_tp_array'),
    sa.CheckConstraint('confidence IS NULL OR confidence BETWEEN 0 AND 100', name='ck_signal_confidence'),
    sa.CheckConstraint('risk_reward IS NULL OR risk_reward > 0', name='ck_signal_rr'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['strategy_code'], ['strategies.code'], ),
    sa.ForeignKeyConstraint(['symbol'], ['symbol_settings.symbol'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_uid')
    )
    op.create_index('idx_signals_lookup', 'signals', ['symbol', 'timeframe', 'strategy_code', 'action', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_signals_status_created', 'signals', ['status', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('group_strategy_symbols',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('setting_id', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['setting_id'], ['group_strategy_settings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symbol'], ['symbol_settings.symbol'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('setting_id', 'symbol', name='uq_gss_symbol')
    )
    op.create_index('idx_group_strategy_symbols_setting', 'group_strategy_symbols', ['setting_id'], unique=False)
    op.create_index('idx_group_strategy_symbols_symbol', 'group_strategy_symbols', ['symbol', 'setting_id'], unique=False)
    op.create_table('group_strategy_timeframes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('setting_id', sa.BigInteger(), nullable=False),
    sa.Column('timeframe', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("timeframe IN ('M5', 'M15', 'H1', 'H4')", name='ck_gss_tf_timeframe'),
    sa.ForeignKeyConstraint(['setting_id'], ['group_strategy_settings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('setting_id', 'timeframe', name='uq_gss_timeframe')
    )
    op.create_index('idx_group_strategy_timeframes_setting', 'group_strategy_timeframes', ['setting_id'], unique=False)
    op.create_index('idx_group_strategy_timeframes_timeframe', 'group_strategy_timeframes', ['timeframe', 'setting_id'], unique=False)
    op.create_table('signal_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('signal_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_signal_events_signal', 'signal_events', ['signal_id', 'created_at'], unique=False)
    op.create_table('telegram_outbox',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('delivery_uid', sa.Text(), nullable=False),
    sa.Column('signal_id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('group_strategy_setting_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Text(), server_default='PENDING', nullable=False),
    sa.Column('send_mode', sa.Text(), server_default='FULL', nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('parse_mode', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default='3', nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.Text(), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('telegram_message_id', sa.Text(), nullable=True),
    sa.Column('locked_by', sa.Text(), nullable=True),
    sa.Column('lock_token', sa.Text(), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("send_mode IN ('BASIC', 'FULL', 'SUMMARY')", name='ck_outbox_send_mode'),
    sa.CheckConstraint("status IN ('PENDING', 'SENDING', 'SENT', 'FAILED_RETRYABLE', 'FAILED_PERMANENT', 'SKIPPED')", name='ck_outbox_status'),
    sa.CheckConstraint('attempt_count <= max_attempts', name='ck_outbox_attempt_le_max'),
    sa.CheckConstraint('attempt_count >= 0', name='ck_outbox_attempt_count'),
    sa.CheckConstraint('max_attempts > 0', name='ck_outbox_max_attempts'),
    sa.ForeignKeyConstraint(['group_id'], ['telegram_groups.id'], ),
    sa.ForeignKeyConstraint(['group_strategy_setting_id'], ['group_strategy_settings.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delivery_uid')
    )
    op.create_index('idx_telegram_outbox_group_status', 'telegram_outbox', ['group_id', 'status', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_telegram_outbox_pending', 'telegram_outbox', ['status', 'next_attempt_at'], unique=False, postgresql_where=sa.text("status IN ('PENDING', 'FAILED_RETRYABLE')"))
    op.create_index('idx_telegram_outbox_signal', 'telegram_outbox', ['signal_id'], unique=False)
    op.create_index('idx_telegram_outbox_stale_lock', 'telegram_outbox', ['locked_until'], unique=False, postgresql_where=sa.text("status = 'SENDING'"))
    op.create_table('signal_deliveries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('outbox_id', sa.BigInteger(), nullable=False),
    sa.Column('delivery_uid', sa.Text(), nullable=False),
    sa.Column('signal_id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('http_status_code', sa.Integer(), nullable=True),
    sa.Column('telegram_message_id', sa.Text(), nullable=True),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('SENDING', 'SENT', 'FAILED_RETRYABLE', 'FAILED_PERMANENT')", name='ck_delivery_status'),
    sa.CheckConstraint('attempt_no > 0', name='ck_delivery_attempt_no'),
    sa.CheckConstraint('http_status_code IS NULL OR http_status_code BETWEEN 100 AND 599', name='ck_delivery_http_status'),
    sa.ForeignKeyConstraint(['group_id'], ['telegram_groups.id'], ),
    sa.ForeignKeyConstraint(['outbox_id'], ['telegram_outbox.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('outbox_id', 'attempt_no', name='uq_delivery_outbox_attempt')
    )
    op.create_index('idx_signal_deliveries_outbox', 'signal_deliveries', ['outbox_id', 'attempt_no'], unique=False)
    op.create_index('idx_signal_deliveries_status', 'signal_deliveries', ['status', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_signal_deliveries_status', table_name='signal_deliveries')
    op.drop_index('idx_signal_deliveries_outbox', table_name='signal_deliveries')
    op.drop_table('signal_deliveries')
    op.drop_index('idx_telegram_outbox_stale_lock', table_name='telegram_outbox', postgresql_where=sa.text("status = 'SENDING'"))
    op.drop_index('idx_telegram_outbox_signal', table_name='telegram_outbox')
    op.drop_index('idx_telegram_outbox_pending', table_name='telegram_outbox', postgresql_where=sa.text("status IN ('PENDING', 'FAILED_RETRYABLE')"))
    op.drop_index('idx_telegram_outbox_group_status', table_name='telegram_outbox')
    op.drop_table('telegram_outbox')
    op.drop_index('idx_signal_events_signal', table_name='signal_events')
    op.drop_table('signal_events')
    op.drop_index('idx_group_strategy_timeframes_timeframe', table_name='group_strategy_timeframes')
    op.drop_index('idx_group_strategy_timeframes_setting', table_name='group_strategy_timeframes')
    op.drop_table('group_strategy_timeframes')
    op.drop_index('idx_group_strategy_symbols_symbol', table_name='group_strategy_symbols')
    op.drop_index('idx_group_strategy_symbols_setting', table_name='group_strategy_symbols')
    op.drop_table('group_strategy_symbols')
    op.drop_index('idx_signals_status_created', table_name='signals')
    op.drop_index('idx_signals_lookup', table_name='signals')
    op.drop_table('signals')
    op.drop_index('idx_market_candles_source_lookup', table_name='market_candles')
    op.drop_index('idx_market_candles_lookup', table_name='market_candles')
    op.drop_table('market_candles')
    op.drop_index('idx_group_strategy_settings_strategy_active', table_name='group_strategy_settings')
    op.drop_index('idx_group_strategy_settings_group_active', table_name='group_strategy_settings')
    op.drop_table('group_strategy_settings')
    op.drop_index('idx_data_source_feeds_status', table_name='data_source_feeds')
    op.drop_index('idx_data_source_feeds_matrix', table_name='data_source_feeds')
    op.drop_table('data_source_feeds')
    op.drop_index('idx_broker_symbol_mappings_source_symbol', table_name='broker_symbol_mappings')
    op.drop_table('broker_symbol_mappings')
    op.drop_table('telegram_groups')
    op.drop_table('symbol_settings')
    op.drop_table('strategies')
    op.drop_table('data_sources')
    op.drop_table('component_health')
    op.drop_index('idx_admin_activity_logs_lookup', table_name='admin_activity_logs')
    op.drop_index('idx_admin_activity_logs_created', table_name='admin_activity_logs')
    op.drop_table('admin_activity_logs')
    # ### end Alembic commands ###
